Repository kuzzleio/kuzzle-vault, pull requests merged in 2019-09, with the labels that each got.

#1 Standalone vault
  .eslintrc.json
  .gitignore
  .npmignore
  .travis.yml
  README.md
  index.js
  lib/vault.js
  package-lock.json
  package.json
  test/vault.test.js
Labels: changelog:new-feature

#2 Release 1.0.0
  .eslintrc.json
  .gitignore
  .npmignore
  .travis.yml
  README.md
  index.js
  lib/vault.js
  package-lock.json
  package.json
  test/vault.test.js
Labels: release

#3 Add sha256 support with old md5 support
  lib/vault.js
  test/vault.test.js
Labels: enhancement
